# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: ltler/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_oneplus_sm8150
          kernel-dir: msm-4.14
          kernel-branch: lineage-23.0
          config: vendor/sm8150-perf_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 16
          aosp-clang-version: r547379
          disable-lto: true
          anykernel3: true
          nethunter: true
          nethunter-patch: true
