# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: ltler/kernel_build_action@main
        with:
          kernel-url: https://github.com/yaap/kernel_oneplus_sm8150
          kernel-dir: msm-4.14
          kernel-branch: sixteen
          config: gulch_defconfig
          arch: arm64
          aosp-gcc:  false
          aosp-clang: true
          extra-cmds: |
             export CROSS_COMPILE_COMPAT=arm-linux-androideabi-
             export CC=clang
             export LLVM=1
             export LLVM_IAS=0
          other-clang-url: 
           https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-security-16.0.0_r3/clang-r536225/bin.tar.gz
          ksu-version: main
          android-version: 12
          aosp-clang-version: r536225
          disable-lto: false
          nethunter: true
          nethunter-patch: false
          anykernel3: true
          extra-cmds: |
             export CROSS_COMPILE_COMPAT=arm-linux-androideabi-
             export CC=clang
             export LLVM=1
             export LLVM_IAS=0
